const Constants = {
  MISSING_FIELDS: "Missing fields",
  USER_ID_REQUIRED: "User ID is required",
  EMAIL_IN_USE: "Email is already in use",
  CREATED_SUCCESSFULLY: "created successfully",
  RETRIEVED_SUCCESSFULLY: "Data retrieved successfully",
  DELETED_SUCCESSFULLY: "Data deleted successfully",
  REGISTERED_SUCCESSFULLY: "User registered successfully",
  UPDATED_SUCCESSFULLY: "Data updated successfully",
  PPRODUCT_CREATED_SUCCESSFULLY: "Product created successfully",
  LOGGED_IN_SUCCESSFULLY: "User logged in successfully",
  NOT_FOUND: "Not found",
  INVALIDA_OBJECTID: "Invalid object",
  INVALID_CREDENTIALS: "Invalid credentials",
  INTERNAL_ERROR: "Internal Server Error",
  ERROR_CREATING_POST: "Error creating post",
  TITLE_MIN_LENGTH: "Title must be at least 3 characters",
  CONTENT_NOT_EMPTY: "Content cannot be empty",
  USERNAME_MIN_LENGTH: "Username must be at least 3 characters",
  INVALID_EMAIL: "Please provide a valid email address",
  PASSWORD_NOT_EMPTY: "Password cannot be empty",
  PASSWORD_MIN_LENGTH: "Password must be at least 6 characters",
  PRODUCT_CREATED_SUCCESSFULLY: "Product Created Successfully",
  PRODUCT_NOT_FOUND: "Product not found!",
  PRODUCT_UPDATED_SUCCESSFULLY: "Product Updated Successfully",
  PRODUCT_DELETED_SUCCESSFULLY: "Product Deleted Successfully",
  JOB_CREATED_SUCCESSFULLY: "Job Created Successfully",
  JOB_NOT_FOUND: "Job not found!",
  JOB_UPDATED_SUCCESSFULLY: "Job Updated Successfully",
  JOB_DELETED_SUCCESSFULLY: "Job marked as deleted!",
  SELECTED_PRODUCT_NOT_FOUND: "Selected product not found!",
  INVALID_FINANCIAL_VALUES: "Invalid tax, subtotal, or total value!",
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  JOB_ALREADY_CONVERTED: "Job Already Converted",
  JOB_CONVERTED_SUCCESSFULLY: "JOb converted successfully",
  TITLE_REQUIRED: "Title is required.",
  TAGS_ARRAY_REQUIRED: "Tags must be an array.",
  NOTES_OPTIONAL: "Notes is optional.",
  PRODUCT_NAME_REQUIRED: "Product name is required.",
  DESCRIPTION_OPTIONAL: "Description is optional.",
  PRICE_NUMERIC_REQUIRED: "Price must be a numeric value.",
  INVOICE_TITLE_REQUIRED: "Invoice title is required.",
  PRODUCT_ID_REQUIRED: "Product ID is required.",
  INVALID_PRODUCT_ID: "Invalid Product ID.",
  TAX_NUMERIC_REQUIRED: "Tax must be a numeric value.",
  SUBTOTAL_NUMERIC_REQUIRED: "Subtotal must be a numeric value.",
  TOTAL_NUMERIC_REQUIRED: "Total must be a numeric value.",
  CONNECTED_TO_MONGODB: "Connected to MongoDB Atlas!",
  CONNECTION_ERROR_MONGODB: "Error connecting to MongoDB Atlas",
  INVOICE_DELETED_SUCCESSFULLY: "Invoice deleted successfully",
  PRODUCT_DELETED_SUCCESSFULLY : "product deleted successfully",
  POSITIVE_NUMBER : "Should be positive number",
  TAGS_FORMAT: 'Tags must be a comma-separated list',

};

module.exports = Constants;
